import Head from "next/head";
//Componensts Import Here
import Layout from "../components/Layout/Layout";
import CarouselTest from "../components/Testing/Carousel";

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Jupiterfull.png" />
      </Head>
      <Layout>
        {/* <h1 className='text-red-500'>Talwind</h1> */}
        {/* <Account/> */}
        <CarouselTest />
        {/* <Slider /> */}
      </Layout>
    </div>
  );
}
