import Head from 'next/head'
import Image from 'next/image'


//CSS Imports Here
import styles from '../styles/Home.module.css'
//Componensts Import Here
import Layout from '../components/Layout/Layout'
import Account from './account'
import CarouselTest from '../components/Testing/Carousel';
import Slider from '../components/Carsouel/Slider';
import $ from 'jquery';
import Login from '../components/omcustomlogin/Login'
import {images} from '../components/Carsouel/SliderImages';
import CatalogMenu from '../components/CatalogMenu/CatalogMenu'


export default function Home() {
  return (
    <div>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Jupiterfull.png" />
      </Head>
        <Layout>
         
        </Layout>

    </div>
  )
}
